# Generated by Django 5.2.7 on 2026-03-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('squat', 'Squat'), ('pushup', 'Pushup'), ('deadlift', 'Deadlift')], max_length=50)),
                ('input_video', models.FileField(upload_to='uploads/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('rep_feedback', models.JSONField(default=list)),
                ('llm_summary', models.TextField(blank=True)),
                ('total_reps', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
