# Generated by Django 5.2.7 on 2026-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analysis_user_alter_analysis_input_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='video_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='video_width',
            field=models.IntegerField(default=0),
        ),
    ]
