# Generated by Django 5.2.7 on 2026-04-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysis_video_height_analysis_video_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='video_height',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='video_width',
        ),
    ]
